#pragma kernel CSMain

StructuredBuffer<float3> positions;
StructuredBuffer<float3> velocities;

RWStructuredBuffer<float3> newPositions;
RWStructuredBuffer<float3> newVelocities;

cbuffer Params
{
    int entityCount;
    float deltaTime;
    float3 targetPos;
    float neighborRadius; //Para alineamiento y cohesión
    float separationRadius; //Para separación
    float maxVel;
    float maxForce;
    float weightSeparation;
    float weightAlignment;
    float weightCohesion;
    float weightTarget;
}

[numthreads(256, 1, 1)]
void CSMain(uint id : SV_DispatchThreadID)
{
    if (id.x >= (uint) entityCount)
        return;
    //Obtención de posición y velocidad:
    float3 pos = positions[id.x];
    float3 vel = velocities[id.x];
    //Inicialización de términos:
    float3 separation = float3(0, 0, 0);
    int separationCount = 0;
    float3 alignment = float3(0, 0, 0);
    int neighborCount = 0;
    float3 cohesion = float3(0, 0, 0);
    
    for (int i = 0; i < entityCount; i++)
    {
        if ((uint) i == id.x)
            continue;
        float3 sep = pos - positions[i];
        float dist = length(sep);
        if (dist > 0 && dist < separationRadius)
        {
            separation += sep / (dist * dist);
            separationCount++;
        }
        if (dist > 0 && dist < neighborRadius)
        {
            alignment += velocities[i];
            cohesion += positions[i];
            neighborCount++;
        }
    }
    if (separationCount > 0)
        separation /= separationCount;
    if (neighborCount > 0)
    {
        alignment = alignment / neighborCount - vel;
        cohesion = cohesion / neighborCount - pos;
    } 
    //Cálculo de velocidad y posición finales:
    float3 targetForce = normalize(targetPos - pos);
    float3 force = weightSeparation * separation + weightAlignment * alignment + 
    weightCohesion * cohesion + weightTarget * targetForce;
    if (length(force) > maxForce)
        force = normalize(force) * maxForce;
    vel += force * deltaTime;
    if (length(vel) > maxVel)
        vel = normalize(vel) * maxVel;
    newVelocities[id.x] = vel;
    newPositions[id.x] = pos + vel * deltaTime;
}