#pragma kernel CSMain

RWStructuredBuffer<float3> positions;
RWStructuredBuffer<float3> targetPositions;
RWStructuredBuffer<float3> velocities;
RWStructuredBuffer<float> restTimers;

cbuffer Params
{
    int entityCount;
    float deltaTime;
    float time;
    float2 speedRange;
    float distThreshold; //Threshold used to check if the target position has been reached
    float2 boundsX;
    float2 boundsY;
    float2 boundsZ;
    float2 restRange;
}

float Random(float id) //Between 0 and 1
{
    return frac(sin(id * 12.9898 + time * 78.233) * 43758.5453);
}

float RandomRange(float id, float minVal, float maxVal)
{
    return minVal + (maxVal - minVal) * Random(id);
}

[numthreads(256, 1, 1)]
void CSMain(uint id : SV_DispatchThreadID)
{
    if (id >= (uint) entityCount)
        return;
    //If the entity is resting its velocity will be 0, which will stop the animation
    if (restTimers[id] > 0)
    {
        velocities[id] = float3(0, 0, 0);
        restTimers[id] -= deltaTime;
        return;
    }
    //If it reaches its destination, a new target position is chosen and a new rest time is established
    if (distance(targetPositions[id], positions[id]) < distThreshold)
    {
        float pos_x = RandomRange(id * 17, boundsX.x, boundsX.y);
        float pos_y = RandomRange(id * 31, boundsY.x, boundsY.y);
        float pos_z = RandomRange(id * 73, boundsZ.x, boundsZ.y);
        targetPositions[id] = float3(pos_x, pos_y, pos_z);
        restTimers[id] = RandomRange(id * 101, restRange.x, restRange.y);
        return;
    }
    //If it isn't resting but its velocity = 0, a new random velocity is chosen
    if (length(velocities[id]) == 0)
    {
        float3 dir = normalize(targetPositions[id] - positions[id]);
        velocities[id] = dir * RandomRange(id * 13, speedRange.x, speedRange.y);
    }
    //Updates its position depending on the speed
    positions[id] += velocities[id] * deltaTime;
}