#pragma kernel CSMain

RWStructuredBuffer<float3> positions;
RWStructuredBuffer<float3> targetPositions;
RWStructuredBuffer<float3> velocities;
RWStructuredBuffer<float> restTimers;

cbuffer Params
{
    int entityCount;
    float deltaTime;
    float time;
    float2 speedRange;
    float distThreshold; //Distancia a partir de la cual considera que ha llegado a su destino
    float2 boundsX;
    float2 boundsY;
    float2 boundsZ;
    float2 restRange;
}

float Random(float id) //Entre 0 y 1
{
    return frac(sin(id * 12.9898 + time * 78.233) * 43758.5453);
}

float RandomRange(float id, float minVal, float maxVal)
{
    return minVal + (maxVal - minVal) * Random(id);
}

[numthreads(256, 1, 1)]
void CSMain(uint id : SV_DispatchThreadID)
{
    if (id >= (uint) entityCount)
        return;
    //Si está descansando tiene velocidad 0, lo cual para la animación
    if (restTimers[id] > 0)
    {
        velocities[id] = float3(0, 0, 0);
        restTimers[id] -= deltaTime;
        return;
    }
    //Si llega al destino elige una nueva posición a la que ir y establece un tiempo de descanso
    if (distance(targetPositions[id], positions[id]) < distThreshold)
    {
        float pos_x = RandomRange(id * 17, boundsX.x, boundsX.y);
        float pos_y = RandomRange(id * 31, boundsY.x, boundsY.y);
        float pos_z = RandomRange(id * 73, boundsZ.x, boundsZ.y);
        targetPositions[id] = float3(pos_x, pos_y, pos_z);
        restTimers[id] = RandomRange(id * 101, restRange.x, restRange.y);
        return;
    }
    //Si está parado pero no está descansando ni en el destino escoge una velocidad aleatoria
    if (length(velocities[id]) == 0)
    {
        float3 dir = normalize(targetPositions[id] - positions[id]);
        velocities[id] = dir * RandomRange(id * 13, speedRange.x, speedRange.y);
    }
    //Actualiza su posición dependiendo de la velocidad
    positions[id] += velocities[id] * deltaTime;
}